#!/bin/bash
# Activate an env profile for the dashboard by copying it to frontend/.env.local,
# then restart the dev server so the new values are picked up.
#
# Usage: scripts/env/use-profile.sh localnet|devnet
set -euo pipefail

PROFILE="${1:-}"
ROOT="/Users/mac/codes/Shadow Desk"
FRONTEND="$ROOT/frontend"
PORT=3001

case "$PROFILE" in
  localnet|devnet) ;;
  *) echo "usage: $0 localnet|devnet"; exit 2 ;;
esac

SOURCE="$FRONTEND/.env.$PROFILE"

# The localnet profile holds no credentials, so generate it when missing. The
# devnet profile carries OIDC credentials and must be created by hand.
if [ ! -f "$SOURCE" ] && [ "$PROFILE" = "localnet" ]; then
  cat > "$SOURCE" <<'ENV'
# Generated by scripts/env/use-profile.sh - local Canton sandbox.
SHADOWDESK_NETWORK=localnet
SHADOWDESK_PARTICIPANT1_URL=http://127.0.0.1:6864
SHADOWDESK_PARTICIPANT2_URL=http://127.0.0.1:18003
SHADOWDESK_CANTON_ACCESS_TOKEN=
SHADOWDESK_CANTON_REFRESH_TOKEN=
SHADOWDESK_LEDGER_USER_ID=
SHADOWDESK_BUYER_PARTY=
SHADOWDESK_RISK_OFFICER_PARTY=
SHADOWDESK_DEALER_A_PARTY=
SHADOWDESK_DEALER_B_PARTY=
SHADOWDESK_ASSET_TO_BUY=cTBILL
SHADOWDESK_SETTLEMENT_ASSET=cUSDC
SHADOWDESK_AMOUNT=1000000
SHADOWDESK_MAX_PRICE=101
ENV
  echo "==> generated $SOURCE"
fi

if [ ! -f "$SOURCE" ]; then
  echo "!! missing profile $SOURCE"
  echo "   create it by copying your working devnet config:"
  echo "   cp frontend/.env.local frontend/.env.devnet"
  exit 1
fi

cp "$SOURCE" "$FRONTEND/.env.local"
echo "==> active profile: $PROFILE (frontend/.env.local)"

echo "==> stopping dashboard on :$PORT"
pkill -f "next dev" 2>/dev/null || true
pkill -f "next-server" 2>/dev/null || true
sleep 2

if [ "$PROFILE" = "devnet" ]; then
  if [ ! -f "$FRONTEND/node_modules" ]; then
    (cd "$FRONTEND" && npm install)
  fi
fi

echo "==> starting dashboard on http://localhost:$PORT"
: > /tmp/shadowdesk-dev.log
FRONTEND_DIR="$FRONTEND" python3 - <<'PY'
import os
import subprocess

cwd = os.environ["FRONTEND_DIR"]
log = open("/tmp/shadowdesk-dev.log", "ab")
process = subprocess.Popen(
    ["npm", "run", "dev"],
    stdout=log,
    stderr=log,
    cwd=cwd,
    env=dict(os.environ),
    start_new_session=True,
)
print(f"    dashboard launcher pid={process.pid}")
PY

for i in $(seq 1 60); do
  if curl -sf -m 2 -o /dev/null "http://localhost:$PORT/api/state"; then
    echo "==> dashboard ready after ${i}s: http://localhost:$PORT"
    exit 0
  fi
  sleep 1
done

echo "!! dashboard did not come up; tail of /tmp/shadowdesk-dev.log:"
tail -20 /tmp/shadowdesk-dev.log
exit 1